### ISSUE TITLE
Interface does not differentiate between Celsius and Farenheit

### ISSUE THREAD

**Issue by maximvoven** [lurgh/infinitive#3]
MQTT and JSON API do not state the units used for temperature.  This makes home assistant bug out depending on how the data is interpreted depending on which config provides the data. Bus logs coming soon.
![Screenshot 2024-02-18 at 6 59 11 PM](https://github.com/lurgh/infinitive/assets/33429176/041ec855-eca4-4d81-85e4-3a069b5fbb21)
![Screenshot 2024-02-18 at 7 05 47 PM](https://github.com/lurgh/infinitive/assets/33429176/521ee466-7b69-423b-a4c8-54bcf5c0d453)

**Comment by maximvoven** [comment]
First Batch of Logs: 
17:15 switched from C to F
17:17 switched from F to C
[resplog.24021819.txt](https://github.com/lurgh/infinitive/files/14325941/resplog.24021819.txt)

**Comment by lurgh** [comment]
Thanks for getting in touch about this.  I am not clear yet what exactly is going wrong for you, other than maybe that the UI card is showing in °F.

My Inifinty system is set to °F and that's the default for my HomeAssistant.  I don't think infinitive has temp units baked in but there could be something going on.  Best I recall, the serial API is consistently just using the units that the system is set to, and we are passing the values through as we see them.  If needed, we could detect the temp units from the system and label the values to/from MQTT but I don't know if it is necessary or how the mqtt climate integration would react.

Maybe try setting ```temperature_unit: C``` in the mqtt climate definitions and see if that stabilizes it for you?  Or let me know more about what's happening on the HA side and we can figure it out.

**Comment by lurgh** [comment]
closing due to lack of response
